<a href="https://colab.research.google.com/github/gloehh/Data-Analitik-Tugas-3-Numpy-Arrays/blob/main/Numpy_Arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
my_list = [1,2,3]
my_list

[1, 2, 3]

In [ ]:
np.array(my_list)

array([1, 2, 3])

In [ ]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
np.arange (0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.arange (0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [7]:
np.zeros (3)

array([0., 0., 0.])

In [8]:
np.zeros ((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [9]:
np.ones (3)

array([1., 1., 1.])

In [10]:
np.ones ((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [11]:
np.linspace (0,10,3)

array([ 0.,  5., 10.])

In [12]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [13]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [14]:
np.random.rand(2)

array([0.9026193 , 0.72010948])

In [15]:
np.random.rand(5,5)

array([[0.13893961, 0.31788013, 0.57246066, 0.5441498 , 0.01821701],
       [0.56192787, 0.24105489, 0.13206306, 0.23468474, 0.51313724],
       [0.5368926 , 0.37048251, 0.92218325, 0.52448458, 0.11092202],
       [0.52541862, 0.42425329, 0.61229112, 0.28596192, 0.13717079],
       [0.95491843, 0.06514562, 0.911874  , 0.51976509, 0.82642592]])

In [16]:
np.random.randn(2)

array([ 0.33139101, -0.77131172])

In [17]:
np.random.randn(5,5)

array([[ 0.14843955,  0.75637367,  1.65739361, -1.59862338, -0.02472698],
       [-0.53329915,  1.19226887, -0.01569446,  1.318473  ,  0.44259582],
       [ 0.44103792, -0.55335955,  1.04807645, -1.48061891, -0.02783482],
       [ 0.17820546,  0.55215299, -0.58654021, -0.01478814,  1.41317051],
       [ 0.36649393, -1.42361867, -0.2334773 ,  0.76451095, -0.61549292]])

In [18]:
np.random.randint(1,100)

64

In [19]:
np.random.randint(1,100,10)

array([33, 74, 40, 15, 41, 26, 37, 21, 58, 96])

In [22]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [23]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [24]:
ranarr

array([ 3,  7, 27, 18, 43, 28, 25, 31, 37, 27])

In [25]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [26]:
ranarr

array([ 3,  7, 27, 18, 43, 28, 25, 31, 37, 27])

In [27]:
ranarr.max()

np.int64(43)

In [28]:
ranarr.argmax()

np.int64(4)

In [29]:
ranarr.min()

np.int64(3)

In [30]:
ranarr.argmin()

np.int64(0)

In [31]:
#Vector
arr.shape

(25,)

In [32]:
#Notice the two sets of brackets
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [33]:
arr.reshape(1,25).shape

(1, 25)

In [34]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [35]:
arr.reshape(25,1).shape

(25, 1)

In [36]:
arr.dtype

dtype('int64')